### ISSUE TITLE
MC-225335

### ISSUE THREAD

**Issue by dsb987** [enqorman/old-animations#1]
Hi! lowercasebtw.
I'm coming from MC-225335 and hearing that you had made a mod to fix this camera bug.
这个模组应该是old-animations吧，但是我好像找不到这个选项耶。。。

**Comment by lowercasebtw** [comment]
Yes, I have a fix for it.

**Comment by lowercasebtw** [comment]
I'm not home atm though, and haven't pushed the code. You'll have to wait until I get home before I can share.

**Comment by dsb987** [comment]
ok，thank you。

**Comment by lowercasebtw** [comment]
As of commit af4c59f, the code now contains a accurate working fix for Bobbing View Tilt (MC-225335)

**Comment by dsb987** [comment]
wowaaaaaaaaaaaaaaaaaaa！！！！！！！！！！！！！！！
thank you！！！！！！！！！！！！！！！！！！！my god！！！！！！！！
wohu！
太谢谢你啦！！！

**Comment by dsb987** [comment]
wowaaaaaaaaaaaaaaaaaaa！！！！！！！！！！！！！！！
thank you！！！！！！！！！！！！！！！！！！！my god！！！！！！！！
wohu！
太谢谢你啦！！！
