### ISSUE TITLE
The effect of the potion is not displayed（药水效果不显示）

### ISSUE THREAD

**Issue by dsb987** [enqorman/old-animations#2]
In Hypixel, the potion effects assigned to players by the server are almost not displayed, while the Vanilla Status HUD option is turned on. However, in single player mode, the effect of the potion is displayed normally.（在hypixel里，服务器赋予玩家的药水效果常常未被显示，而此时Vanilla Status HUD选项是开启的。不过在单人模式下，药水效果显示正常。）
with not VIA mod （没有使用VIA模组）

**Comment by dsb987** [comment]
哦对了，我用的是1.20.6版本的old-animations（build #7 [b13cda4]）
我希望您能继续提供对1.20.6的更新支持。
鉴于1.21刚发布没多久，漏洞还比较多，且相应的模组也未更新到1.21，也许把开发重心放到1.20.6上会是更好的选择。

**Comment by lowercasebtw** [comment]
I'll look into making a 1.20.x branch, but for now I would like to continue working on the 1.21 version till I can fix up a lot of issues it has currently, and clean up the code.

I am currently taking a break from working on this mod.

**Comment by lowercasebtw** [comment]
我会考虑制作一个 1.20.x 分支，但目前我想继续开发 1.21 版本，直到我可以修复它目前存在的许多问题并清理代码。

我目前正在暂停开发这个 mod。

(Google Translate "https://translate.google.com/")

**Comment by dsb987** [comment]
Thank you for your development
I hope that one day this mod can become popular!
