### ISSUE TITLE
Great Job, couple things

### ISSUE THREAD

**Issue by Polisvh** [enqorman/old-animations#3]
Hi! I see you doing a great job over here
May I tho ask you for some stuff
If you are working to add back swordblocking animation, can you please make it so it does not require a shield in your offhand, so it actually causes an animation whether you use your right click 
Labymod for example, has this feature inside their client - it's called ClassicPvP, it would be great if you could recreate it!

There is also another thing from Labymod - do you know that when you use your shield, there is a 1  tick long animation that shows that the shield raises to block
I would appreciate if you added an option to remove this "raising animation" so it instantly goes into "blocking" pose
Talking about shield - it would be really great if you made it so you could perform swinging animation or digging animation while blocking with a shield in main hand (there are servers out there that retexture shields to swords with custommodeldata so they can actually recreate "1.8 blocking" animation)

here is a source code to a creater who managed to code swing/dig animations while using items such as pulling your bow, eating food and even sword blocking without shield, (tho it does not look perfect with the sword block animation there):

https://github.com/jordoncodes/OldAnimationsFabric

**Comment by lowercasebtw** [comment]
I don't know about that, as that would be changing vanilla mechanics and this mod aims to try and not do that, the only thing that I've changed remotely is sneaking and I put a warning over that.

**Comment by lowercasebtw** [comment]
The shield blocking is for compatibility with servers that use ViaVersion or some other plugin to allow joining from newer versions on a 1.8 server, for example Hypixel does this.

**Comment by Polisvh** [comment]
My friend, the warning could also be put under the swordblock without shield mechanics

What about the swinging animation while using items such as
Eating food
Pulling bow
Blocking with shield
? What do you think about that? Is it difficult (I sent you source code to someone who achieved it)
Also about removing the raise animation from blocking shield 

Me myself I aim to use this mod on servers that do not use viaversion but are purely 1.21 that try to imitate 1.8 pvp but want to also implement new version features

**Comment by Polisvh** [comment]
LabyMod's Classic PvP animations do thay
When you are right clicking with a sword, you perform a blocking animation, BUT
- you are still able to run (you do not slowdown)
- you can still deal damage and take damage
- its pure visual, doesnt affect the gameplay
If that would be possible to recreate - I'd be the most thankful

Also I really am trying to find a mod that removes this "raise animation" on shield, in LabyMod this feature is called "ItemSwitch" that by description should work like removing the cooldown animation when switching between items

**Comment by lowercasebtw** [comment]
Take a look at https://github.com/Mixces/Legacy-Animations/ for the time being

**Comment by lowercasebtw** [comment]
I'm taking a break from working on this mod as im busy IRL

**Comment by lowercasebtw** [comment]
I'm splitting this mod into multiple as I feel that is the better things to do.
